name: Check Emacs Lisp

on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'

  workflow_dispatch:

jobs:
  byte-compile:
    uses: akirak/cosmetic-transient.el/.github/workflows/build-emacs-lisp.yml@workflow-call
    with:
      melpa-flake: github:akirak/melpa/akirak

